//sign
export const CREATE_TOKEN = 'CREATE_TOKEN' //创建token
export const CREATE_USERINFO = 'CREATE_USERINFO'//生成用户信息
export const DELETE = 'DELETE' //删除sessionStore

//titleSet
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const CHANGE_TITLE_INDEX = 'CHANGE_TITLE_INDEX'

//orderList
export const ORDER_SET_EACH_ORDER = 'ORDER_SET_EACH_ORDER'
export const ORDER_UPDATE_ROW_CONTEXT = 'ORDER_UPDATE_ROW_CONTEXT'
export const ORDER_DELETE_ROW = 'ORDER_DELETE_ROW'
export const ORDER_UPDATE_ROW = 'ORDER_UPDATE_ROW'
export const ORDER_SAVE_TMP_ROW = 'ORDER_SAVE_TMP_ROW'

//orderDiaglog
export const ORDER_SET_DIALOG = 'ORDER_SET_DIALOG'
export const ORDER_ADD_EDIT = 'ORDER_ADD_EDIT'
export const ORDER_OPEN_DIALOG = 'ORDER_OPEN_DIALOG'
export const ORDER_CLOSE_DIALOG = 'ORDER_CLOSE_DIALOG'

//orderEidt
export const ORDER_UPADTE_VALUE = 'ORDER_UPADTE_VALUE'
export const ORDER_INIT_EDIT_FORM = 'ORDER_INIT_EDIT_FORM'

//memberList
export const MEMBER_SET_EACH_ORDER = 'MEMBER_SET_EACH_ORDER'
export const MEMBER_UPDATE_ROW_CONTEXT = 'MEMBER_UPDATE_ROW_CONTEXT'
export const MEMBER_DELETE_ROW = 'MEMBER_DELETE_ROW'
export const MEMBER_UPDATE_ROW = 'MEMBER_UPDATE_ROW'
export const MEMBER_SAVE_TMP_ROW = 'MEMBER_SAVE_TMP_ROW'

//memberDiaglog
export const MEMBER_OPEN_DIALOG = 'MEMBER_OPEN_DIALOG'
export const MEMBER_CLOSE_DIALOG = 'MEMBER_CLOSE_DIALOG'
export const MEMBER_SET_DIALOG = 'MEMBER_SET_DIALOG'
export const MEMBER_ADD_EDIT = 'MEMBER_ADD_EDIT'

//memberEidt
export const MEMBER_UPADTE_VALUE = 'MEMBER_UPADTE_VALUE'
export const MEMBER_INIT_EDIT_FORM = 'MEMBER_INIT_EDIT_FORM'
